### ISSUE TITLE
TP AED K1051 Consulta Equipo

### ISSUE THREAD

**Issue by josemariasola** [facumarin/Hello-World#1]
Buen día, Marin,

Necesito me confirmes en qué equipo aportaste las resoluciones del TP.

Gracias.

Esp. Ing. José María Sola
Profesor
UTN FRBA

**Comment by facumarin** [comment]
Buen dia profesor,

                                   Perdon por no responder antes,  estuve con algunos problemas personales.

El grupo al que pertenezco es al 5. Estuve realizando el TP con Edgar Vasquez. Tuve un problema con el teléfono, me dejo de funcionar WhatsApp y perdí los contactos en enero mientras estaba de vacaciones (la fabrica en la cual trabajo cerro por mes y medio). Ayer volví y pude recuperar el nro. de Edgar y me dijo que el había enviado el TP pensando que yo había dejado la materia porque me había salido del grupo de WhatsApp.


Le paso la dirección donde esta subido el TP


https://github.com/edvasquez/TP_2016_AED

Saludos.

PD: Lo estaremos modificando a la brevedad para agregar mi nombre.


________________________________
De: José María Sola <notifications@github.com>
Enviado: domingo, 19 de febrero de 2017 10:02 a.m.
Para: facumarin/Hello-World
Cc: Subscribed
Asunto: [facumarin/Hello-World] TP AED K1051 Consulta Equipo (#1)


Buen día, Marin,

Necesito me confirmes en qué equipo aportaste las resoluciones del TP.

Gracias.

Esp. Ing. José María Sola
Profesor
UTN FRBA
